export const actionTypes = {
  GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  SINGLE_ITEM: "SINGLE_ITEM",
  MONEY_SYMBOL: "MONEY_SYMBOL",
  SELECTED: "SELECTED",
};
